# Generated by Django 5.2.16 on 2026-07-08 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnesthasiaTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Constraints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rule_type', models.CharField(choices=[('HARD', 'Hard Constraint (Kesin)'), ('SOFT', 'Soft Constraint(Esnek)')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OperationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('room_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Surgeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('off_day', models.CharField(blank=True, choices=[('Pazartesi', 'Pazartesi'), ('Salı', 'Salı'), ('Çarşamba', 'Çarşamba'), ('Perşembe', 'Perşembe'), ('Cuma', 'Cuma')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('operation_name', models.CharField(max_length=100)),
                ('required_specialty', models.CharField(max_length=200)),
                ('duration_slots', models.IntegerField()),
                ('priority', models.CharField(choices=[('Düşük', 'Düşük'), ('Orta', 'Orta'), ('Yüksek', 'Yüksek'), ('Kritik', 'Kritik')], max_length=20)),
                ('required_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.operationroom')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('start_slot', models.IntegerField()),
                ('end_slot', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.operationroom')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.anesthasiateam')),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.surgeon')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.surgery')),
            ],
        ),
    ]
