# Generated by Django 5.2.16 on 2026-07-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnesthasiaTeam',
            new_name='AnesthesiaTeam',
        ),
    ]
