# Generated by Django 5.2.16 on 2026-07-10 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_rename_anesthasiateam_anesthesiateam'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='surgeon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.surgeon'),
        ),
    ]
