# Generated by Django 5.2.16 on 2026-07-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_schedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraints',
            name='name',
            field=models.CharField(choices=[('priority_weight', 'Öncelik Ağırlığı (Sıralama)'), ('duration_weight', 'Süre Ağırlığı (Sıralama)'), ('surgeon_off_day', 'Cerrah İzin Günü'), ('max_daily_surgeries', 'Cerrah Başı Günlük Maksimum Ameliyat'), ('min_rest_slots', 'Ameliyatlar Arası Minimum Dinlenme (Slot)')], max_length=100, unique=True),
        ),
    ]
